"""
Task Manager Models
"""

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Custom User model linked to AWS Cognito
    """
    cognito_id = models.CharField(max_length=255, unique=True, null=True, blank=True)
    email = models.EmailField(unique=True)

    # Fix reverse accessor clashes
    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        related_name='custom_user_set',
        related_query_name='custom_user',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='custom_user_set',
        related_query_name='custom_user',
    )

    class Meta:
        db_table = 'users'

    def __str__(self):
        return self.email


class Task(models.Model):
    """
    Task model
    """
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
    ]

    CATEGORY_CHOICES = [
        ('personal', 'Personal'),
        ('work', 'Work'),
        ('urgent', 'Urgent'),
        ('other', 'Other'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    category = models.CharField(
        max_length=20,
        choices=CATEGORY_CHOICES,
        null=True,
        blank=True
    )
    priority = models.IntegerField(
        null=True,
        blank=True,
        help_text="Priority level 1-5, where 5 is highest"
    )
    ai_classified = models.BooleanField(
        default=False,
        help_text="Whether this task has been classified by AI"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'status']),
            models.Index(fields=['user', 'category']),
            models.Index(fields=['user', '-created_at']),
        ]
        db_table = 'tasks'

    def __str__(self):
        return f"{self.title} ({self.status})"


class Subtask(models.Model):
    """
    Subtask model - can be created manually or by AI
    """
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='subtasks')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    completed = models.BooleanField(default=False)
    order = models.IntegerField(default=0, help_text="Display order")
    ai_generated = models.BooleanField(
        default=False,
        help_text="Whether this subtask was generated by AI"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order', 'created_at']
        db_table = 'subtasks'

    def __str__(self):
        return f"{self.title} ({'✓' if self.completed else '○'})"


class AIAnalysis(models.Model):
    """
    AI Analysis tracking - stores AI interactions for audit and debugging
    """
    ANALYSIS_TYPES = [
        ('classification', 'Classification'),
        ('subtask_generation', 'Subtask Generation'),
        ('full_analysis', 'Full Analysis'),
    ]

    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='ai_analyses'
    )
    analysis_type = models.CharField(max_length=50, choices=ANALYSIS_TYPES)
    prompt = models.TextField(help_text="The prompt sent to the AI")
    response = models.TextField(help_text="The AI's response")
    model_used = models.CharField(
        max_length=50,
        help_text="Which model was used (e.g., llama3.2:3b)"
    )
    tokens_used = models.IntegerField(
        null=True,
        blank=True,
        help_text="Number of tokens used (if available)"
    )
    duration_ms = models.IntegerField(
        null=True,
        blank=True,
        help_text="Time taken in milliseconds"
    )
    success = models.BooleanField(default=True)
    error_message = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        db_table = 'ai_analyses'
        verbose_name_plural = 'AI Analyses'

    def __str__(self):
        return f"{self.analysis_type} for {self.task.title} ({self.created_at})"
